// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm3Mo9n3CM7aCBLfxjO56oykJaQcVShqM',
    appId: '1:1018904515960:web:109e2932774b3fcbb1e48d',
    messagingSenderId: '1018904515960',
    projectId: 'agendamento-8a10c',
    authDomain: 'agendamento-8a10c.firebaseapp.com',
    storageBucket: 'agendamento-8a10c.appspot.com',
    measurementId: 'G-DZHQLCL2FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbYroM6BGIUwBXsye6Q_J8SB17EVo3Kgs',
    appId: '1:1018904515960:android:09c11780194996beb1e48d',
    messagingSenderId: '1018904515960',
    projectId: 'agendamento-8a10c',
    storageBucket: 'agendamento-8a10c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQtsh_SH0IWvyvNomxiywxB29ZcfwAOMY',
    appId: '1:1018904515960:ios:5c6ecae906330657b1e48d',
    messagingSenderId: '1018904515960',
    projectId: 'agendamento-8a10c',
    storageBucket: 'agendamento-8a10c.appspot.com',
    iosBundleId: 'com.example.agendaNailApp',
  );
}
